spring:
  application:
    name: spring-boot-togglz-demo
  jpa:
    hibernate:
      ddl-auto: update
    database: db2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: sa
    driverClassName: org.h2.Driver

togglz:
  enabled: true
  console:
   enabled: true
   path: /togglz-console
   secured: false